= 05-hello-install
:toc:
:toc-placement!:

toc::[]

== Introduction

This example shows how to generate a `make install` target to install files and
binaries on your system. This is based on the previous shared library example.

The files in this tutorial are below:

[source]
----
05-hello-install$ tree
.
├── cmake-examples.conf
├── CMakeLists.txt
├── include
│   └── Hello.h
├── README.adoc
└── src
    ├── Hello.cpp
    └── main.cpp
----

  * link:CMakeLists.txt[CMakeLists.txt] - Contains the CMake commands you wish to run
  * link:cmake-hello-install.conf[cmake-hello-install.conf] - An example configuration file
  * link:include/hello.hpp[include/hello.hpp] - The header file to include
  * link:src/hello.cpp[src/hello.cpp] - A source file to compile
  * link:src/main.cpp[src/main.cpp] - The source file with main

== Concepts

=== Installing

CMake offers the ability to add a `make install` target to allow a user to
install binaries, libraries and other files. The base install location is controlled
by the variable +CMAKE_INSTALL_PREFIX+ which can be set using cmake or by calling
cmake with `cmake .. -DCMAKE_INSTALL_PREFIX=/install/location`

The files that are installed are controlled by the https://cmake.org/cmake/help/latest/command/install.html[+install()+] function.

[source,cmake]
----
install(
    TARGETS ${BINARY_NAME}
    DESTINATION "install library target"
)
----

Install the binary generated from the target ${BINARY_NAME} target to
the destination +${CMAKE_INSTALL_PREFIX}/bin+

[source,cmake]
----
install(
    TARGETS ${LIBRARY_NAME}
    LIBRARY
    DESTINATION "install library target"
)
----

Install the shared library generated from the target ${LIBRARY_NAME} target to
the destination +${CMAKE_INSTALL_PREFIX}/lib+

[source,cmake]
----
install(
    DIRECTORY ${PROJECT_SOURCE_DIR}/include/
    DESTINATION "include file path"
)
----

Install the header files for developing against the +${LIBRARY_NAME}+ library
into the +${CMAKE_INSTALL_PREFIX}/include+ directory.

[source,cmake]
----
install(
    FILES cmake-hello-install.conf
    DESTINATION "install config"
)
----

Install a configuration file to the destination +${CMAKE_INSTALL_PREFIX}/etc+

After `make install` has been run, CMake generates an install_manifest.txt file
which includes details on all installed files.

[NOTE]
====
If you run the `make install` command as root, the install_manifest.txt file will
be owned by root.
====

== Building the Example

[source,bash]
----
$ mkdir build

$ cd build/

$ cmake ..
-- The C compiler identification is ...
-- The CXX compiler identification is ...
-- Check for working C compiler: ...
-- Check for working C compiler: ... -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: ...
-- Check for working CXX compiler: ... -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Configuring done
-- Generating done
-- Build files have been written to: project-abusolute-path/05-hello-install/build

$ make
Scanning dependencies of target ${LIBRARY_NAME}
[ 50%] Building CXX object CMakeFiles/${LIBRARY_NAME}.dir/src/hello.cpp.o
Linking CXX static library lib${LIBRARY_NAME}.so
[ 50%] Built target ${LIBRARY_NAME}
Scanning dependencies of target ${BINARY_NAME}
[100%] Building CXX object CMakeFiles/${BINARY_NAME}.dir/src/main.cpp.o
Linking CXX executable ${BINARY_NAME}
[100%] Built target ${BINARY_NAME}

$ sudo make install
[sudo] password for your_user_name:
[ 50%] Built target ${LIBRARY_NAME}
[100%] Built target ${BINARY_NAME}
Install the project...
-- Install configuration: ""
-- Installing: /usr/local/bin/${BINARY_NAME}
-- Removed runtime path from "/usr/local/bin/${BINARY_NAME}"
-- Installing: /usr/local/lib/lib${LIBRARY_NAME}.so
-- Installing: /usr/local/etc/cmake-hello-install.conf

$ cat install_manifest.txt
/usr/local/bin/${BINARY_NAME}
/usr/local/lib/lib${LIBRARY_NAME}.so
/usr/local/etc/cmake-hello-install.conf
----

[NOTE]
====
If `/usr/local/lib` is not in your library path you may need to add it to the
path before running the binary.
====

[[extra-notes]]
Extra Notes
~~~~~~~~~~~

[[default-location]]
Overriding the default install location
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

As mentioned the default install location is set from +CMAKE_INSTALL_PREFIX+,
which defaults to `/usr/local/`

If you want to change this default location for all users you can add the
following code to your top level CMakeLists.txt before adding any binaries or
libraries.

[source,cmake]
----
if(CMAKE_INSTALL_PREFIX_INITIALIZED_TO_DEFAULT)
  message(STATUS "Setting default CMAKE_INSTALL_PREFIX path to ${CMAKE_BINARY_DIR}/install")
  set(CMAKE_INSTALL_PREFIX "${CMAKE_BINARY_DIR}/install" CACHE STRING "The path to use for make install" FORCE)
endif()
----

This example sets the default install location to under your build directory.

[[destdir]]
DESTDIR
^^^^^^^

If you wish to stage your install to confirm that all files are included the
`make install` target supports the DESTDIR argument.

[source]
----
make install DESTDIR=/tmp/stage
----

This will create the install path `${DESTDIR}/${CMAKE_INSTALL_PREFIX}` for all
your installation files. In this example, it would install all files under the
path `/tmp/stage/usr/local`

[source]
----
$ tree /tmp/stage
/tmp/stage
└── usr
    └── local
        ├── bin
        │   └── ${BINARY_NAME}
        ├── etc
        │   └── cmake-hello-install.conf
        └── lib
            └── lib${LIBRARY_NAME}.so
----

[[uninstall]]
Uninstall
^^^^^^^^^

By default, CMake does not add a `make uninstall` target. For details on how to generate
an uninstallation target see this https://gitlab.kitware.com/cmake/community/-/wikis/FAQ#can-i-do-make-uninstall-with-cmake[FAQ]

For an easy way to remove the files from this example, you can use:

[source]
----
sudo xargs rm < install_manifest.txt
----
