= 02-vendoring-code
:toc:
:toc-placement!:

toc::[]

== Introduction

link:https://stackoverflow.com/questions/26217488/what-is-vendoring[Vendoring] code means to include the third party code inside your repository and build it as part of your project.
It is a way to ensure that all files required to build your project are part of the development environment.

== Implementation

=== Including 3rd Party Code

Typically, this might take the form or a `3rd-party` or `vendor` directory,
in which you copy the source of the libraries you want to include. For example, you may do something like:

[source]
----
01-google-test$ tree
.
├── 3rd_party
│       └── googletest
│           └── cmake
│               ├── google-test.cmake
│               └── google_test.in
├── cmake
│       └── prepare-3rd-party.cmake
├── cmake
│       ├── test1.hpp
│       └── test1.cpp
├── CMakeList.txt
└── main.cpp
----

If these projects support CMake directly, it may be possible to do `add_subdirectory()` / `include()` on the libraries folder and have that project build and be made available to your code.

If the third party code doesn't support CMake, you may need to create a "shim" layer on top of the project to allow it to be build and discovered from CMake.

=== Using git to vendor code

A slightly different method to include the third party code can be to use your SCM software to manage the process for you. 

In the case of git, you can use link:https://git-scm.com/book/en/v2/Git-Tools-Submodules[git sub-modules].
These can pull the correct version of the third party code into your repository on initialisation / update.

== Examples

A simple example of vendoring code can already be seen in the link:../../004-unit-test/01-google-test/[google-test] tutorial.
