= 02-protobuf
:toc:
:toc-placement!:

toc::[]

== Introduction

This example shows how to generate source files using https://github.com/google/protobuf[protobuf].
Protocol Buffers is a data serialization format from Google. A user provides a
`.proto` file with a description of the data. Then using the protobuf compiler, the proto file
can be translated into source code in a number of languages including C++.

The files in this tutorial are below:

[source]
----
02-protobuf$ tree
.
├── AddressBook.proto
├── CMakeLists.txt
├── main.cpp
----

  * link:library.proto[library.proto] - proto file from main protocol buffer https://developers.google.com/protocol-buffers/docs/cpptutorial[example]
  * link:CMakeLists.txt[CMakeLists.txt] - Contains the CMake commands you wish to run
  * link:main.cpp[main.cpp] - The source file from the protobuf example.

== Requirements

This example requires the protocol buffers binary and libraries to be installed.

This can be installed on Ubuntu using

[source,bash]
----
sudo apt-get install protobuf-compiler libprotobuf-dev
----

== Concepts

=== Exported Variables

The variables exported by the CMake protobuf package and used in this example include:

  * `PROTOBUF_FOUND` - If Protocol Buffers is installed
  * `PROTOBUF_INCLUDE_DIRS` - The protobuf header files
  * `PROTOBUF_LIBRARIES` - The protobuf library

More variables are defined and can be found by examining the documentation at the
top of your `FindProtobuf.cmake` file.

=== Generating Source

The protobuf CMake package includes a number of helper functions to make the
code generation easier. In this example we are generating C++ source and use
the following code:

[source,cmake]
----
PROTOBUF_GENERATE_CPP(
		PROTO_SRCS PROTO_HDRS
		library.proto
)
----

The arguments are:

  * PROTO_SRCS - Name of the variable that will store the .pb.cc files.
  * PROTO_HDRS- Name of the variable that will store the .pb.h files.
  * library.proto - The .proto file to generate code from.

=== Generated Files

After the `PROTOBUF_GENERATE_CPP` function is called, you will have the above-mentioned variables available.
These will be marked as the output to a custom command
which calls the protobuf compiler binary to generate them.

To then have the files generated you should add them to a library or executable.
For example:

[source,cmake]
----
add_executable(
		${PROJECT_NAME}
		main.cpp
		${PROTO_SRCS}
		${PROTO_HDRS}
)
----

This will cause the protobuf compiler to be called when you call `make` on that
executables target.

When changes are made to the .proto file, the associated source files will be
autogenerated again. However, if no changes are made to the .proto file and you re-run
make, then nothing will be done.

== Building the Example

[source,bash]
----
$ mkdir build

$ cd build/

$ cmake ..
-- The C compiler identification is ...
-- The CXX compiler identification is ...
-- Check for working C compiler: ...
-- Check for working C compiler: ... -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: ...
-- Check for working CXX compiler: ... -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Build files have been written to: project-absolute-path/02-protobuf/build

$ make
balabala

$ ls
library.pb.cc  CMakeCache.txt  cmake_install.cmake  ${PROJECT_NAME}
library.pb.h   CMakeFiles      Makefile

$ ./${PROJECT_NAME} test_library
----
